name: multibaas_example
version: 1.0.0
description: MultiBaas Example for Dart
homepage: https://curvegrid.com
publish_to: none

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  multibaas:
    path: ../
  built_value: any
  built_collection: any
  dio: any
